# action.yml
name: app-state-diagram
description: Produces a full application state diagram and hyperlinked documentation from ALPS profile
inputs:
  config:
    description: Config file
    required: true
    default: profile.xml
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.config }}
